[build]
command = "npx vite build"
publish = "dist"
functions = "netlify/functions"


[[redirects]]
from = "/api/gemini/ephemeral"
to = "/.netlify/functions/ephemeral"
status = 200
force = true


[[redirects]]
from = "/*"
to = "/index.html"
status = 200
